// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
#endif

#import "/Users/kevinmcquown/Dropbox/WCL/Launch/Contracts/cellarworx2/CellarworxKit/CellarworxKit/CellarworxKit-Bridging-Header.h"

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC13CellarworxKit7Actions")
@interface Actions : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) BOOL inprogress;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger ordernumber;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit12Additiondata")
@interface Additiondata : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit9Additions")
@interface Additions : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull innoculationbrand;
@property (nonatomic, copy) NSString * _Nonnull labtest;
@property (nonatomic) NSInteger bleedamount;
@property (nonatomic) NSInteger brix;
@property (nonatomic) NSInteger dapamount;
@property (nonatomic) NSInteger daycount;
@property (nonatomic) NSInteger goamount;
@property (nonatomic) NSInteger htaamount;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger innoculationamount;
@property (nonatomic) NSInteger superfoodamt;
@property (nonatomic) NSInteger wateramount;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit12Appellations")
@interface Appellations : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Assets")
@interface Assets : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull location;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull owner;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic) BOOL hidden;
@property (nonatomic) float coneheight;
@property (nonatomic) float cylinderdiameter;
@property (nonatomic) float cylinderheight;
@property (nonatomic) float initialgallons;
@property (nonatomic) float liddiameter;
@property (nonatomic) float tankcapheight;
@property (nonatomic) NSInteger capacity;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger order;
@property (nonatomic, getter=typeid, setter=setTypeid:) NSInteger typeid_;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit10Assettypes")
@interface Assettypes : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger capacity;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Badges")
@interface Badges : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull devtoken;
@property (nonatomic) NSInteger sorting;
@property (nonatomic) NSInteger todo;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit13Barrelhistory")
@interface Barrelhistory : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) float pressfraction;
@property (nonatomic) NSInteger barrelnumber;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit7Barrels")
@interface Barrels : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull clientcode;
@property (nonatomic, copy) NSString * _Nonnull forest;
@property (nonatomic, copy) NSString * _Nonnull initialvarietal;
@property (nonatomic, copy) NSString * _Nonnull number;
@property (nonatomic, copy) NSString * _Nonnull other;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic, copy) NSString * _Nonnull toast;
@property (nonatomic, copy) NSString * _Nonnull vineyard;
@property (nonatomic) NSInteger capacity;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger initialusedcount;
@property (nonatomic) NSInteger yearnew;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit9Bindetail")
@interface Bindetail : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull misc;
@property (nonatomic) NSInteger bincount;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger tare;
@property (nonatomic) NSInteger weight;
@property (nonatomic) NSInteger weightag;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Blend")
@interface Blend : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit10Blenditems")
@interface Blenditems : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic, copy) NSString * _Nonnull sourcelot;
@property (nonatomic) float gallons;
@property (nonatomic) NSInteger blendid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit3Bol")
@interface Bol : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull bond;
@property (nonatomic, copy) NSString * _Nonnull carrier;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull clientcode;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull zip;
@property (nonatomic) float cost;
@property (nonatomic) NSInteger facilityid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit15Bolitembreakout")
@interface Bolitembreakout : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull appellation;
@property (nonatomic, copy) NSString * _Nonnull varietal;
@property (nonatomic, copy) NSString * _Nonnull vineyard;
@property (nonatomic) float percentage;
@property (nonatomic) NSInteger bolitemsid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger vintage;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Bolitems")
@interface Bolitems : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull clientcode;
@property (nonatomic, copy) NSString * _Nonnull lot;
@property (nonatomic) float gallons;
@property (nonatomic) float gallonspercase;
@property (nonatomic) float palletcount;
@property (nonatomic) NSInteger bolid;
@property (nonatomic) NSInteger bottlespercase;
@property (nonatomic) NSInteger casecount;
@property (nonatomic) NSInteger casesperpallet;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger partialpalletcasecount;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Bottling")
@interface Bottling : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull labelapproval;
@property (nonatomic) float gallonspercase;
@property (nonatomic) NSInteger estcasecount;
@property (nonatomic) NSInteger finalcasecount;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Brixtemp")
@interface Brixtemp : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull lot;
@property (nonatomic, copy) NSString * _Nonnull vessel;
@property (nonatomic) float brix;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger temp;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit15Buffertitration")
@interface Buffertitration : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) float initialph;
@property (nonatomic) float naoh1;
@property (nonatomic) float naoh2;
@property (nonatomic) float naoh3;
@property (nonatomic) float naoh4;
@property (nonatomic) float naoh5;
@property (nonatomic) float naoh6;
@property (nonatomic) float naoh7;
@property (nonatomic) float ph1;
@property (nonatomic) float ph2;
@property (nonatomic) float ph3;
@property (nonatomic) float ph4;
@property (nonatomic) float ph5;
@property (nonatomic) float ph6;
@property (nonatomic) float ph7;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger labresultsid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Client")
@interface Client : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull bond;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull clientname;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull group;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull zip;
@property (nonatomic) BOOL active;
@property (nonatomic) BOOL ap;
@property (nonatomic) NSInteger clientid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class User;
@class NSError;

@interface Client (SWIFT_EXTENSION(CellarworxKit))
@property (nonatomic, copy) NSArray<User *> * _Nonnull users;
+ (void)getClients:(BOOL)active complete:(void (^ _Nonnull)(NSArray<Client *> * _Nonnull, NSError * _Nullable))complete;
@end


SWIFT_CLASS("_TtC13CellarworxKit11CompanyInfo")
@interface CompanyInfo : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull favicon;
@property (nonatomic, copy) NSString * _Nonnull lat;
@property (nonatomic, copy) NSString * _Nonnull logourl;
@property (nonatomic, copy, getter=long, setter=setLong:) NSString * _Nonnull long_;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull zip;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit9DevTokens")
@interface DevTokens : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull devtoken;
@property (nonatomic, copy) NSString * _Nonnull udid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger userid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Fermprot")
@interface Fermprot : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull clientcode;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic, copy) NSString * _Nonnull lot;
@property (nonatomic, copy) NSString * _Nonnull vesselid;
@property (nonatomic) BOOL brixtemp;
@property (nonatomic) BOOL dryice;
@property (nonatomic) BOOL pd;
@property (nonatomic) BOOL po2;
@property (nonatomic) BOOL stir;
@property (nonatomic) float stattemp;
@property (nonatomic) NSInteger additionid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger pdendbrix;
@property (nonatomic) NSInteger pdendbrix2;
@property (nonatomic) NSInteger pdfreq;
@property (nonatomic) NSInteger pdfreq2;
@property (nonatomic) NSInteger pdstartbrix;
@property (nonatomic) NSInteger pdstartbrix2;
@property (nonatomic) NSInteger poam;
@property (nonatomic) NSInteger poduration;
@property (nonatomic) NSInteger poduration2;
@property (nonatomic) NSInteger poendbrix;
@property (nonatomic) NSInteger poendbrix2;
@property (nonatomic) NSInteger pofreq;
@property (nonatomic) NSInteger pofreq2;
@property (nonatomic) NSInteger ponoon;
@property (nonatomic) NSInteger popm;
@property (nonatomic) NSInteger postartbrix;
@property (nonatomic) NSInteger postartbrix2;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Files")
@interface Files : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull filetype;
@property (nonatomic, copy) NSString * _Nonnull location;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger size;
@property (nonatomic) NSInteger theid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit10Filllevels")
@interface Filllevels : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) BOOL correction;
@property (nonatomic) NSInteger amount;
@property (nonatomic) NSInteger bottlingid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Flags")
@interface Flags : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) float value;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Fpaddmap")
@interface Fpaddmap : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger additionid;
@property (nonatomic) NSInteger fermprotid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Groups")
@interface Groups : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger groupid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit10Labresults")
@interface Labresults : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic, copy) NSString * _Nonnull units1;
@property (nonatomic, copy) NSString * _Nonnull units2;
@property (nonatomic) float value1;
@property (nonatomic) float value2;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger labtestid;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit7Labtest")
@interface Labtest : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull labtestnumber;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit12Labtestcosts")
@interface Labtestcosts : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull labtest;
@property (nonatomic) float cost;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit9Locations")
@interface Locations : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull appellation;
@property (nonatomic, copy) NSString * _Nonnull applemoth;
@property (nonatomic, copy) NSString * _Nonnull bondnumber;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull gatecode;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull region;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull zip;
@property (nonatomic) float lat;
@property (nonatomic, getter=long, setter=setLong:) float long_;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit12Lotfavorites")
@interface Lotfavorites : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull lotnumber;
@property (nonatomic) BOOL favorite;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit7Lotlist")
@interface Lotlist : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger lotid;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit4Lots")
@interface Lots : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull lotnumber;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic) BOOL activelot;
@property (nonatomic) BOOL favorite;
@property (nonatomic) BOOL organic;
@property (nonatomic) NSInteger clientcode;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger theorder;
@property (nonatomic) NSInteger year;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Messages")
@interface Messages : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Newwos")
@interface Newwos : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull devtoken;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Notes")
@interface Notes : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger ordernumber;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit6Orders")
@interface Orders : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull company;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull firstname;
@property (nonatomic, copy) NSString * _Nonnull lastname;
@property (nonatomic, copy) NSString * _Nonnull ordercomment;
@property (nonatomic, copy) NSString * _Nonnull orderstatus;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull ship_address1;
@property (nonatomic, copy) NSString * _Nonnull ship_address2;
@property (nonatomic, copy) NSString * _Nonnull ship_city;
@property (nonatomic, copy) NSString * _Nonnull ship_company;
@property (nonatomic, copy) NSString * _Nonnull ship_firstname;
@property (nonatomic, copy) NSString * _Nonnull ship_lastname;
@property (nonatomic, copy) NSString * _Nonnull ship_phone;
@property (nonatomic, copy) NSString * _Nonnull ship_state;
@property (nonatomic, copy) NSString * _Nonnull ship_zip;
@property (nonatomic, copy) NSString * _Nonnull shipclass;
@property (nonatomic, copy) NSString * _Nonnull shipmethod;
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSString * _Nonnull zip;
@property (nonatomic) float shipping_cost;
@property (nonatomic) float skuprice;
@property (nonatomic) float total_order_amount;
@property (nonatomic) NSInteger custid;
@property (nonatomic) NSInteger customerid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger ordernumber;
@property (nonatomic) NSInteger skuqty;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit8Packages")
@interface Packages : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic, copy) NSString * _Nonnull trackingnumber;
@property (nonatomic) NSInteger actionid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit19PressRoomActivities")
@interface PressRoomActivities : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) BOOL completed;
@property (nonatomic) BOOL inpressroom;
@property (nonatomic) NSInteger dbid;
@property (nonatomic) NSInteger scp;
@property (nonatomic) NSInteger sequencenumber;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit12Pressprogram")
@interface Pressprogram : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull program;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic) float presscut;
@property (nonatomic) NSInteger filllevel;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger pressduration;
@property (nonatomic) NSInteger settlingtime;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit7Program")
@interface Program : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) BOOL repeating;
@property (nonatomic) NSInteger day;
@property (nonatomic) NSInteger daycount;
@property (nonatomic) NSInteger fermprotid;
@property (nonatomic) NSInteger highbrix;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger lowbrix;
@property (nonatomic) NSInteger wotemplateid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit11PushDevices")
@interface PushDevices : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull devtoken;
@property (nonatomic) BOOL sorting;
@property (nonatomic) BOOL todo;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit11Reservation")
@interface Reservation : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull forlot;
@property (nonatomic) BOOL inuse;
@property (nonatomic) float tonsinvessel;
@property (nonatomic) NSInteger assetid;
@property (nonatomic) NSInteger bincount;
@property (nonatomic) NSInteger custid;
@property (nonatomic) NSInteger daysrequired;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Roles")
@interface Roles : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger personid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit3Scp")
@interface Scp : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull apc;
@property (nonatomic, copy) NSString * _Nonnull appellation;
@property (nonatomic, copy) NSString * _Nonnull clone;
@property (nonatomic, copy) NSString * _Nonnull colorcode;
@property (nonatomic, copy) NSString * _Nonnull notes;
@property (nonatomic, copy) NSString * _Nonnull proposedlot;
@property (nonatomic, copy) NSString * _Nonnull specialinstructions;
@property (nonatomic, copy) NSString * _Nonnull varietal;
@property (nonatomic, copy) NSString * _Nonnull vineyard;
@property (nonatomic) BOOL handsorting;
@property (nonatomic) BOOL inpressroom;
@property (nonatomic) BOOL ontable;
@property (nonatomic) float actualtons;
@property (nonatomic) float esttons;
@property (nonatomic) NSInteger estdaysintank;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger processingspeed;
@property (nonatomic) NSInteger sulphurppm;
@property (nonatomic) NSInteger vineyardid;
@property (nonatomic) NSInteger wholecluster;
@property (nonatomic) NSInteger woid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit22SortingTableActivities")
@interface SortingTableActivities : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) BOOL completed;
@property (nonatomic) BOOL ontable;
@property (nonatomic) NSInteger dbid;
@property (nonatomic) NSInteger scp;
@property (nonatomic) NSInteger sequencenumber;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit13Surveyanswers")
@interface Surveyanswers : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull comment;
@property (nonatomic, copy) NSString * _Nonnull userid;
@property (nonatomic) BOOL yesnoanswer;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger questionid;
@property (nonatomic) NSInteger scaleanswer;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit15Surveyquestions")
@interface Surveyquestions : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull question;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Tasks")
@interface Tasks : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit4User")
@interface User : PFUser
@property (nonatomic, copy) NSString * _Nonnull cellphone;
@property (nonatomic, copy) NSString * _Nonnull deviceid;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL staffEnum;
@property (nonatomic) NSInteger clientid;
@property (nonatomic) NSInteger group;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit14Usermessagemap")
@interface Usermessagemap : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger messageid;
@property (nonatomic) NSInteger userid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit13Validlabtests")
@interface Validlabtests : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull labtest;
@property (nonatomic, copy) NSString * _Nonnull units;
@property (nonatomic) float max;
@property (nonatomic) float min;
@property (nonatomic) NSInteger decimalplaces;
@property (nonatomic) NSInteger id;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit9Varietals")
@interface Varietals : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull abbreviation;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit7Vessels")
@interface Vessels : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull the_description;
@property (nonatomic) float volume;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger vesselid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit2Wo")
@interface Wo : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull alert;
@property (nonatomic, copy) NSString * _Nonnull assignedto;
@property (nonatomic, copy) NSString * _Nonnull clientcode;
@property (nonatomic, copy) NSString * _Nonnull completeby;
@property (nonatomic, copy) NSString * _Nonnull completeddescription;
@property (nonatomic, copy) NSString * _Nonnull lot;
@property (nonatomic, copy) NSString * _Nonnull otherdesc;
@property (nonatomic, copy) NSString * _Nonnull requestor;
@property (nonatomic, copy) NSString * _Nonnull samplevolume;
@property (nonatomic, copy) NSString * _Nonnull toppinglot;
@property (nonatomic, copy) NSString * _Nonnull vesselid;
@property (nonatomic) BOOL autogenerated;
@property (nonatomic) BOOL brixtemp;
@property (nonatomic) BOOL deleted;
@property (nonatomic) BOOL dryice;
@property (nonatomic) BOOL evening;
@property (nonatomic) BOOL inventoryadjusted;
@property (nonatomic) BOOL morning;
@property (nonatomic) BOOL noon;
@property (nonatomic) float cost;
@property (nonatomic) float endingbarrelcount;
@property (nonatomic) float endingtankgallons;
@property (nonatomic) float stattemp;
@property (nonatomic) NSInteger additionid;
@property (nonatomic) NSInteger assetsid;
@property (nonatomic) NSInteger autotag;
@property (nonatomic) NSInteger brix;
@property (nonatomic) NSInteger duration;
@property (nonatomic) NSInteger endingtoppinggallons;
@property (nonatomic) NSInteger fermprotid;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger labtestid;
@property (nonatomic) NSInteger relatedadditionsid;
@property (nonatomic) NSInteger relatedlabtestid;
@property (nonatomic) NSInteger sampleqty;
@property (nonatomic) NSInteger scpid;
@property (nonatomic) NSInteger so2add;
@property (nonatomic) NSInteger taskid;
@property (nonatomic) NSInteger workareaid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit2Wt")
@interface Wt : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull appellation;
@property (nonatomic, copy) NSString * _Nonnull clone;
@property (nonatomic, copy) NSString * _Nonnull lot;
@property (nonatomic, copy) NSString * _Nonnull trailerlicense;
@property (nonatomic, copy) NSString * _Nonnull trucklicense;
@property (nonatomic, copy) NSString * _Nonnull variety;
@property (nonatomic, copy) NSString * _Nonnull vineyard;
@property (nonatomic, getter=void, setter=setVoid:) BOOL void_;
@property (nonatomic) float cost;
@property (nonatomic) NSInteger clientcode;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger regioncode;
@property (nonatomic) NSInteger scpid;
@property (nonatomic) NSInteger tagid;
@property (nonatomic) NSInteger vineyardid;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13CellarworxKit5Zones")
@interface Zones : PFObject <PFSubclassing>
+ (NSString * _Nonnull)parseClassName;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger number;
- (nonnull instancetype)initWithClassName:(NSString * _Nonnull)newClassName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
